config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: %i[show]
  def index
    @flats = Flat.all
  end

  def show
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flat_path(@flat)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_flat
    @flat = Flat.find(params[:id])
  end

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<div class="container my-3">

  <div class="row justify-content-between">

    <% @flats.each do |flat| %>
      <div class="col-sm p-0 m-3 border">
        <div class="bg-light p-3" style="height: 200px" >
          <p> <strong> <%= flat.name %> </strong></p>
          <p>  <strong>Address:</strong> <%= flat.address %></p>
          <div class="d-flex gap-3">
            <strong> <i class="fa-solid fa-euro-sign"></i> <%= flat.price_per_night %> </strong>
            <strong> <i class="fa-solid fa-users"></i> <%= flat.number_of_guests %> </strong>
          </div>
        </div>
        <div class="p-3">
          <%= link_to flat_path(flat), class:"text-decoration-none text-dark" do %>
            <strong><%= "More info" %></strong>
          <% end %>
        </div>
      </div>
    <% end %>

  </div>

</div>

app/views/flats/new.html.erb
<div class="container">
  <%= simple_form_for @flat do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <%= f.input :price_per_night %>
    <%= f.input :number_of_guests %>
    <%= f.button :submit, class:"btn btn-dark" %>
  <% end %>
</div>

app/views/flats/show.html.erb
<div class="bg-light col-sm m-3 p-3" >
  <p> <strong> <%= @flat.name %> </strong></p>
  <p>  <strong>Address:</strong> <%= @flat.address %></p>
  <p> <%= @flat.description %></p>
  <div class="d-flex gap-3">
    <strong> <i class="fa-solid fa-euro-sign"></i> <%= @flat.price_per_night %> </strong>
    <strong> <i class="fa-solid fa-users"></i> <%= @flat.number_of_guests %> </strong>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <%# bootstrap %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%# font awesome %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">

  </head>

  <body>
    <div class="d-flex justify-content-between bg-light p-3">
      <%= link_to flats_path do%>
        <i class="fa-solid fa-house"></i>
      <% end%>
      <%= link_to new_flat_path, class:"btn btn-dark" do%>
        <%= "Add a new flat" %>
      <% end%>
    </div>
    <%= yield %>
  </body>
</html>